### ISSUE TITLE
[QUESTION] Modifying code to use a different GPU?

### ISSUE THREAD

**Issue by BStenfors9119** [a-rose/obs-headless#5] opened 2023-04-22 18:53 UTC
To Whom This May Concern:

I am not a CPP dev but would love to take a stab at making this work with a different GPU than NVidia, if possible.

Is this at all possible?  If so would you mind pointing me to the areas that would need to be changed?

TIA,
Bryan

**Comment by a-rose** [comment] 2023-04-27 08:10
Hello,

This project uses Docker, specifically Nvidia images for Docker, so you probably need to build and run it out of Docker to use another kind of GPU.
It is doable, originally this project was intended to run outside of Docker and it worked fine. OBS desktop supports all kind of GPUs, so it shouldn't be too much trouble :)

**Comment by BStenfors9119** [comment] 2023-04-29 18:52
Awesome! Thanks and I was wondering because I didn't find anything referring to a specific drive / etc within the code :).

Going to give it a shot of building and running locally.
Ideally if all goes well I am wanting to use this within a product of mine, if that is ok with you?

Thanks!

**Comment by a-rose** [comment] 2023-04-30 11:08
No problem. This makes me think, maybe I should split the actual lib and the Docker stuff in two separate projects.

Sure, you can use obs-headless any way you like. I'm not 100% confident it's production-ready, but if you report issues here I can have a look.
Also, maybe check OBS's license to make sure it fits your work 😉.

**Comment by BStenfors9119** [comment] 2023-05-06 21:37
That would be pretty cool.  

I apologize, I am just now getting back to this.  I keep finding things within my product that I feel needs more attention but this one would be huge if I can get it working how I think it can.  Going to start focusing on this full time pretty soon.

Started working on creating a bash script that is a installer but in doing this I am realizing why you decided on docker.  That way it wouldn't mess with any libraries already installed & working on an existing system.

**Comment by a-rose** [comment] 2023-07-05 07:46
Closing this, but feel free to open another issue if you find anything!

**Closed as completed by a-rose** 2023-07-05 07:46 UTC
